export const initial_comentarios = [{
    idComentario: 1,
    fotoPerfil: "/icones-usuarios/FotoPerfil12.jpg",
    nomeUsuario: "Luiz Tavares",
    assinatura: "Universo" as const,
    dataHora: "2025-11-20 08:21:00",
    temaPergunta: "Como posso ganhar mais pontos e sair do TOP 80921 no rank?",
    conteudoComentario: "Oi pessoal, tô meio preocupado aqui... já faz um tempão que tô no curso e até agora meus pontos tão em ZERO. Todo mundo já tem um monte e eu continuo parado, no final do ranking geral.\n\nEu entro na plataforma sempre que dá, olho umas coisas, clico em umas aulas, mas nada muda. Nem um pontinho sobe! Será que meu perfil tá com problema? Ou só algumas pessoas conseguem ganhar ponto?\n\nNão sei se tem algum segredo escondido que eu não achei ainda... alguém pode me explicar como que faz pra ganhar ponto? Porque tô achando muito estranho eu tá tão atrás de todo mundo.",
    numeroAvaliacao: 0,
    avaliacaoDoUsuario: "esteUsuario",
    eDoUsuario: true,
    tags: ["Dúvida", "Universo"],
    imagemComentario: "src/pages/forum/ImgComentarioTEMP/comentarioImg1.png",
    arrayRespostas: [{
        idResposta: 1,
        rfotoPerfil: "/icones-usuarios/kurbie.jpg",
        rnomeUsuario: "JoonAlvez",
        assinatura: "Órbita" as const,
        rdataHora: "2025-11-20 09:00:00",
        rconteudoComentario: "Você só vai ganhar pontos se completar atividades que o sistema contabiliza. Ver só o conteúdo sem concluir não soma pontos. Faça as avaliações e marque as aulas como concluídas.",
        eDoUsuario: false,
        arrayRespostasAninhadas: [{
            idResposta: 11,
            rfotoPerfil: "/icones-usuarios/FotoPerfil12.jpg",
            rnomeUsuario: "Luiz Tavares",
            assinatura: "Universo" as const,
            rdataHora: "2025-11-20 11:15:00",
            rconteudoComentario: "Obrigado pela dica! Vou começar a marcar as aulas como concluídas. Não sabia que tinha que fazer isso!",
            eDoUsuario: true
        }, {
            idResposta: 12,
            rfotoPerfil: "/icones-usuarios/kurbie.jpg",
            rnomeUsuario: "JoonAlvez",
            assinatura: "Órbita" as const,
            rdataHora: "2025-11-20 12:30:00",
            rconteudoComentario: "Sim! E não esqueça de fazer os exercícios práticos também. Eles valem bastante pontos.",
            eDoUsuario: false
        }]
    }, {
        idResposta: 2,
        rfotoPerfil: "/icones-usuarios/FotoPerfil12.jpg",
        rnomeUsuario: "AgnesSofia",
        assinatura: "Órbita" as const,
        rdataHora: "2025-11-20 10:30:00",
        rconteudoComentario: "Zero pontos até agora? Rapaz, tu deve estar tentando ganhar ponto só de abrir a tela ou de qualquer jeito. xxkkk A plataforma sempre teve um sistema de verdade.",
        eDoUsuario: false,
        arrayRespostasAninhadas: []
    }],
    contagem: false
}, {
    idComentario: 2,
    fotoPerfil: "/icones-usuarios/kurbie.jpg",
    nomeUsuario: "Kurbie",
    assinatura: "Galáxia" as const,
    dataHora: "2025-11-19 10:45:00",
    temaPergunta: "Qual a melhor trilha para iniciantes em programação?",
    conteudoComentario: "Estou começando agora no mundo da programação e me sinto um pouco perdido com a quantidade de linguagens e frameworks. Qual seria a melhor trilha de cursos para um iniciante completo na plataforma? Quero focar em desenvolvimento web, mas não sei por onde começar.",
    numeroAvaliacao: 0,
    avaliacaoDoUsuario: "outroUsuario",
    eDoUsuario: false,
    tags: ["Dúvida", "Galáxia", "Conselho"],
    imagemComentario: null,
    arrayRespostas: [{
        idResposta: 1,
        rfotoPerfil: "/icones-usuarios/FotoPerfil12.jpg",
        rnomeUsuario: "DevMaster",
        assinatura: "Galáxia" as const,
        rdataHora: "2025-11-19 14:20:00",
        rconteudoComentario: "Recomendo começar com HTML, CSS e JavaScript básico. Depois partir para React ou Vue. A trilha de frontend é bem didática aqui na plataforma.",
        eDoUsuario: false,
        arrayRespostasAninhadas: [{
            idResposta: 21,
            rfotoPerfil: "/icones-usuarios/kurbie.jpg",
            rnomeUsuario: "Kurbie",
            assinatura: "Galáxia" as const,
            rdataHora: "2025-11-19 15:45:00",
            rconteudoComentario: "Perfeito! Vou seguir essa ordem então. Muito obrigado pela orientação!",
            eDoUsuario: false
        }]
    }],
    contagem: false
}, {
    idComentario: 3,
    fotoPerfil: "/icones-usuarios/FotoPerfil12.jpg",
    nomeUsuario: "Marina Costa",
    assinatura: "Órbita" as const,
    dataHora: "2025-11-21 14:30:00",
    temaPergunta: "Alguém tem material extra sobre Algoritmos?",
    conteudoComentario: "Estou com dificuldade no módulo de algoritmos e gostaria de saber se alguém tem materiais complementares, exercícios extras ou até mesmo indicação de livros. Os vídeos das aulas estão bons, mas queria praticar mais antes da prova.",
    numeroAvaliacao: 0,
    avaliacaoDoUsuario: "outroUsuario",
    eDoUsuario: false,
    tags: ["Material", "Órbita", "Dúvida"],
    imagemComentario: null,
    arrayRespostas: [{
        idResposta: 31,
        rfotoPerfil: "/icones-usuarios/kurbie.jpg",
        rnomeUsuario: "TechBro_99",
        assinatura: "Galáxia" as const,
        rdataHora: "2025-11-21 15:10:00",
        rconteudoComentario: "Eu usei o site 'Algoritmos Fáceis' e me ajudou muito! Também tem o livro 'Lógica de Programação' do autor José Silva que é excelente.",
        eDoUsuario: false,
        arrayRespostasAninhadas: []
    }],
    contagem: false
}, {
    idComentario: 4,
    fotoPerfil: "/icones-usuarios/kurbie.jpg",
    nomeUsuario: "Pedro Silva",
    assinatura: "Universo" as const,
    dataHora: "2025-11-21 16:45:00",
    temaPergunta: "Bug na plataforma - vídeos não carregam",
    conteudoComentario: "Desde ontem à noite os vídeos das aulas não estão carregando. Já tentei limpar cache, trocar de navegador e até reinstalar o app, mas nada funciona. Alguém mais está com esse problema? Preciso assistir as aulas urgente pois tenho prova amanhã!",
    numeroAvaliacao: 0,
    avaliacaoDoUsuario: "outroUsuario",
    eDoUsuario: false,
    tags: ["Problema", "Universo"],
    imagemComentario: null,
    arrayRespostas: [{
        idResposta: 41,
        rfotoPerfil: "/icones-usuarios/FotoPerfil12.jpg",
        rnomeUsuario: "Suporte Nebula",
        assinatura: "Galáxia" as const,
        rdataHora: "2025-11-21 17:00:00",
        rconteudoComentario: "Olá Pedro! Identificamos o problema e nossa equipe já está trabalhando na correção. Previsão de normalização: 2 horas. Desculpe o transtorno!",
        eDoUsuario: false,
        arrayRespostasAninhadas: [{
            idResposta: 411,
            rfotoPerfil: "/icones-usuarios/kurbie.jpg",
            rnomeUsuario: "Pedro Silva",
            assinatura: "Universo" as const,
            rdataHora: "2025-11-21 17:15:00",
            rconteudoComentario: "Obrigado pelo retorno rápido! Vou aguardar então.",
            eDoUsuario: false
        }]
    }],
    contagem: false
}, {
    idComentario: 5,
    fotoPerfil: "/icones-usuarios/FotoPerfil12.jpg",
    nomeUsuario: "Carla Mendes",
    assinatura: "Galáxia" as const,
    dataHora: "2025-11-22 09:00:00",
    temaPergunta: "Grupo de estudos para a prova de Python",
    conteudoComentario: "Pessoal, estou organizando um grupo de estudos pelo Discord para estudarmos juntos para a prova de Python que vai ser semana que vem. Quem tiver interesse, manda mensagem! Vamos revisar os principais conceitos e fazer exercícios em grupo.",
    numeroAvaliacao: 0,
    avaliacaoDoUsuario: "outroUsuario",
    eDoUsuario: false,
    tags: ["Convite", "Galáxia", "Debate"],
    imagemComentario: null,
    arrayRespostas: [{
        idResposta: 51,
        rfotoPerfil: "/icones-usuarios/kurbie.jpg",
        rnomeUsuario: "Lucas_Dev",
        assinatura: "Órbita" as const,
        rdataHora: "2025-11-22 09:30:00",
        rconteudoComentario: "Eu quero! Como faço para entrar?",
        eDoUsuario: false,
        arrayRespostasAninhadas: []
    }, {
        idResposta: 52,
        rfotoPerfil: "/icones-usuarios/FotoPerfil12.jpg",
        rnomeUsuario: "Ana_Codes",
        assinatura: "Órbita" as const,
        rdataHora: "2025-11-22 10:00:00",
        rconteudoComentario: "Também tenho interesse! Pode mandar o link?",
        eDoUsuario: false,
        arrayRespostasAninhadas: []
    }],
    contagem: false
}, {
    idComentario: 6,
    fotoPerfil: "/icones-usuarios/kurbie.jpg",
    nomeUsuario: "Rafael Tech",
    assinatura: "Órbita" as const,
    dataHora: "2025-11-22 10:30:00",
    temaPergunta: "JavaScript vs TypeScript - qual aprender primeiro?",
    conteudoComentario: "Vi que a plataforma tem cursos tanto de JavaScript quanto de TypeScript. Para quem está começando agora, qual vocês recomendam aprender primeiro? Ouvi dizer que TypeScript é melhor, mas também que é mais difícil. Estou confuso sobre qual caminho seguir.",
    numeroAvaliacao: 0,
    avaliacaoDoUsuario: "outroUsuario",
    eDoUsuario: false,
    tags: ["Dúvida", "Órbita", "Conselho"],
    imagemComentario: null,
    arrayRespostas: [{
        idResposta: 61,
        rfotoPerfil: "/icones-usuarios/FotoPerfil12.jpg",
        rnomeUsuario: "DevSenior",
        assinatura: "Galáxia" as const,
        rdataHora: "2025-11-22 11:00:00",
        rconteudoComentario: "Definitivamente comece com JavaScript! TypeScript é basicamente JavaScript com tipos, então você precisa dominar JS primeiro. Depois que entender bem os conceitos, migrar para TS fica muito mais fácil.",
        eDoUsuario: false,
        arrayRespostasAninhadas: [{
            idResposta: 611,
            rfotoPerfil: "/icones-usuarios/kurbie.jpg",
            rnomeUsuario: "Rafael Tech",
            assinatura: "Órbita" as const,
            rdataHora: "2025-11-22 11:30:00",
            rconteudoComentario: "Perfeito! Vou seguir essa ordem então. Obrigado!",
            eDoUsuario: false
        }]
    }],
    contagem: false
}, {
    idComentario: 7,
    fotoPerfil: "/icones-usuarios/FotoPerfil12.jpg",
    nomeUsuario: "Juliana Santos",
    assinatura: "Universo" as const,
    dataHora: "2025-11-21 08:00:00",
    temaPergunta: "Certificado não foi emitido após conclusão do curso",
    conteudoComentario: "Terminei o curso de React há 3 dias e ainda não recebi meu certificado. Já verifiquei meu email (inclusive spam) e nada. No meu perfil aparece que o curso está 100% concluído. Alguém sabe quanto tempo demora para o certificado ser emitido?",
    numeroAvaliacao: 0,
    avaliacaoDoUsuario: "outroUsuario",
    eDoUsuario: false,
    tags: ["Problema", "Universo"],
    imagemComentario: null,
    arrayRespostas: [],
    contagem: false
}, {
    idComentario: 8,
    fotoPerfil: "/icones-usuarios/kurbie.jpg",
    nomeUsuario: "Bruno Alves",
    assinatura: "Galáxia" as const,
    dataHora: "2025-11-20 20:15:00",
    temaPergunta: "Sugestão: adicionar modo escuro na plataforma",
    conteudoComentario: "Seria incrível se a plataforma tivesse um modo escuro! Estudo principalmente à noite e o fundo branco acaba cansando minha vista depois de algumas horas. Sei que muita gente ia adorar essa funcionalidade. Equipe Nebula, considerem essa sugestão! 🌙",
    numeroAvaliacao: 0,
    avaliacaoDoUsuario: "outroUsuario",
    eDoUsuario: false,
    tags: ["Observação", "Galáxia", "Debate"],
    imagemComentario: null,
    arrayRespostas: [{
        idResposta: 81,
        rfotoPerfil: "/icones-usuarios/FotoPerfil12.jpg",
        rnomeUsuario: "CodeMaster",
        assinatura: "Universo" as const,
        rdataHora: "2025-11-20 21:00:00",
        rconteudoComentario: "+1! Também preciso disso, meus olhos agradecem antecipadamente.",
        eDoUsuario: false,
        arrayRespostasAninhadas: []
    }],
    contagem: false
}, {
    idComentario: 9,
    fotoPerfil: "/icones-usuarios/FotoPerfil12.jpg",
    nomeUsuario: "Thiago Ferreira",
    assinatura: "Órbita" as const,
    dataHora: "2025-11-22 07:30:00",
    temaPergunta: "Dúvida sobre exercício de Arrays no módulo 3",
    conteudoComentario: "Alguém conseguiu resolver o exercício 7 do módulo 3 sobre arrays? Estou travado há 2 dias e não consigo entender como fazer a ordenação sem usar o método sort(). O professor pediu para fazer manualmente mas não estou conseguindo.",
    numeroAvaliacao: 0,
    avaliacaoDoUsuario: "outroUsuario",
    eDoUsuario: false,
    tags: ["Dúvida", "Órbita", "Material"],
    imagemComentario: null,
    arrayRespostas: [{
        idResposta: 91,
        rfotoPerfil: "/icones-usuarios/kurbie.jpg",
        rnomeUsuario: "AlgoExpert",
        assinatura: "Galáxia" as const,
        rdataHora: "2025-11-22 08:00:00",
        rconteudoComentario: "Você precisa implementar o Bubble Sort! Basicamente, você compara pares de elementos adjacentes e troca se estiverem na ordem errada. Repete esse processo até não ter mais trocas.",
        eDoUsuario: false,
        arrayRespostasAninhadas: [{
            idResposta: 911,
            rfotoPerfil: "/icones-usuarios/FotoPerfil12.jpg",
            rnomeUsuario: "Thiago Ferreira",
            assinatura: "Órbita" as const,
            rdataHora: "2025-11-22 08:45:00",
            rconteudoComentario: "Ahh entendi! Vou tentar implementar. Valeu!",
            eDoUsuario: false
        }]
    }],
    contagem: false
}, {
    idComentario: 10,
    fotoPerfil: "/icones-usuarios/kurbie.jpg",
    nomeUsuario: "Amanda Lima",
    assinatura: "Universo" as const,
    dataHora: "2025-11-21 13:20:00",
    temaPergunta: "Vale a pena fazer o curso de Node.js antes do React?",
    conteudoComentario: "Pessoal, estou planejando minha trilha de estudos e fiquei na dúvida: é melhor fazer Node.js antes de React ou posso ir direto para React? Já tenho conhecimento sólido de JavaScript. Qual a opinião de vocês?",
    numeroAvaliacao: 0,
    avaliacaoDoUsuario: "outroUsuario",
    eDoUsuario: false,
    tags: ["Conselho", "Universo", "Debate"],
    imagemComentario: null,
    arrayRespostas: [{
        idResposta: 101,
        rfotoPerfil: "/icones-usuarios/FotoPerfil12.jpg",
        rnomeUsuario: "FullStackDev",
        assinatura: "Galáxia" as const,
        rdataHora: "2025-11-21 14:00:00",
        rconteudoComentario: "Pode ir direto para React! Node é backend, React é frontend. São coisas independentes. Depois você pode voltar e fazer Node para completar seu conhecimento fullstack.",
        eDoUsuario: false,
        arrayRespostasAninhadas: []
    }],
    contagem: false
}, {
    idComentario: 11,
    fotoPerfil: "/icones-usuarios/FotoPerfil12.jpg",
    nomeUsuario: "Gabriel Souza",
    assinatura: "Galáxia" as const,
    dataHora: "2025-11-20 16:00:00",
    temaPergunta: "Live de dúvidas sobre SQL - Quando será a próxima?",
    conteudoComentario: "Pessoal, perdi a última live de dúvidas sobre SQL que rolou semana passada. Alguém sabe se ficou gravada? E se tem previsão de quando será a próxima? Estou cheio de dúvidas sobre JOIN e subconsultas.",
    numeroAvaliacao: 0,
    avaliacaoDoUsuario: "outroUsuario",
    eDoUsuario: false,
    tags: ["Dúvida", "Galáxia"],
    imagemComentario: null,
    arrayRespostas: [],
    contagem: false
}, {
    idComentario: 12,
    fotoPerfil: "/icones-usuarios/kurbie.jpg",
    nomeUsuario: "Fernanda Costa",
    assinatura: "Órbita" as const,
    dataHora: "2025-11-22 11:45:00",
    temaPergunta: "Compartilhando meu primeiro projeto! 🎉",
    conteudoComentario: "Gente, acabei de terminar meu primeiro projeto usando React + TypeScript! É um todo list simples mas estou super orgulhosa. Foi muito desafiador mas consegui aplicar tudo que aprendi nos últimos módulos. Quem quiser ver, o link está no meu perfil do GitHub. Aceito feedbacks!",
    numeroAvaliacao: 0,
    avaliacaoDoUsuario: "outroUsuario",
    eDoUsuario: false,
    tags: ["Debate", "Órbita", "Observação"],
    imagemComentario: null,
    arrayRespostas: [{
        idResposta: 121,
        rfotoPerfil: "/icones-usuarios/FotoPerfil12.jpg",
        rnomeUsuario: "CodeReviewer",
        assinatura: "Universo" as const,
        rdataHora: "2025-11-22 12:30:00",
        rconteudoComentario: "Parabéns! Vou dar uma olhada e te mando um feedback. Continua assim!",
        eDoUsuario: false,
        arrayRespostasAninhadas: []
    }],
    contagem: false
}, {
    idComentario: 13,
    fotoPerfil: "/icones-usuarios/FotoPerfil12.jpg",
    nomeUsuario: "Ricardo Nunes",
    assinatura: "Universo" as const,
    dataHora: "2025-11-21 18:30:00",
    temaPergunta: "Erro 404 ao tentar acessar módulo de Git",
    conteudoComentario: "Toda vez que tento acessar as aulas do módulo de Git recebo um erro 404. Já tentei sair e entrar novamente, mas o problema persiste. Outros módulos estão funcionando normalmente. Alguém mais está com esse problema?",
    numeroAvaliacao: 0,
    avaliacaoDoUsuario: "outroUsuario",
    eDoUsuario: false,
    tags: ["Problema", "Universo"],
    imagemComentario: null,
    arrayRespostas: [],
    contagem: false
}, {
    idComentario: 14,
    fotoPerfil: "/icones-usuarios/kurbie.jpg",
    nomeUsuario: "Beatriz Rodrigues",
    assinatura: "Galáxia" as const,
    dataHora: "2025-11-20 09:30:00",
    temaPergunta: "Dicas de como organizar tempo de estudo?",
    conteudoComentario: "Estou tendo dificuldade em organizar meu tempo entre trabalho, estudos e vida pessoal. Vocês que já estão mais avançados, como fazem para manter a consistência nos estudos? Quantas horas por dia conseguem dedicar?",
    numeroAvaliacao: 0,
    avaliacaoDoUsuario: "outroUsuario",
    eDoUsuario: false,
    tags: ["Conselho", "Galáxia", "Debate"],
    imagemComentario: null,
    arrayRespostas: [{
        idResposta: 141,
        rfotoPerfil: "/icones-usuarios/FotoPerfil12.jpg",
        rnomeUsuario: "ProdutividadeMax",
        assinatura: "Universo" as const,
        rdataHora: "2025-11-20 10:15:00",
        rconteudoComentario: "Eu uso a técnica Pomodoro: 25 min de estudo, 5 min de pausa. Consigo estudar 2h por dia dessa forma. O importante é a consistência, não a quantidade!",
        eDoUsuario: false,
        arrayRespostasAninhadas: [{
            idResposta: 1411,
            rfotoPerfil: "/icones-usuarios/kurbie.jpg",
            rnomeUsuario: "Beatriz Rodrigues",
            assinatura: "Galáxia" as const,
            rdataHora: "2025-11-20 11:00:00",
            rconteudoComentario: "Boa! Vou testar essa técnica. Obrigada!",
            eDoUsuario: false
        }]
    }],
    contagem: false
}, {
    idComentario: 15,
    fotoPerfil: "/icones-usuarios/FotoPerfil12.jpg",
    nomeUsuario: "Marcos Paulo",
    assinatura: "Órbita" as const,
    dataHora: "2025-11-22 06:00:00",
    temaPergunta: "Apostila de CSS disponível para download?",
    conteudoComentario: "O professor mencionou na aula que tem uma apostila de CSS com todos os seletores e propriedades. Alguém sabe onde posso baixar? Não achei na área de materiais do curso.",
    numeroAvaliacao: 0,
    avaliacaoDoUsuario: "outroUsuario",
    eDoUsuario: false,
    tags: ["Material", "Órbita", "Dúvida"],
    imagemComentario: null,
    arrayRespostas: [],
    contagem: false
}]